version: "3.3"
services:

  qdrant-db:
    image: qdrant/qdrant:master
    ports:
      - "6333:6333"
    volumes:
      - ./path/to/data:/qdrant/storage
      - ./qdrant/development.yaml:/qdrant/config/development.yaml

  interface:
    build:
      context: ./interface
      dockerfile: ./Dockerfile
    container_name: interface
    ports:
      - "8501:8501"
    volumes:
      - ./queries:/app/queries
      - ./results:/app/results
      - ./data:/app/data

  # api:
  #   build:
  #     context: ./endpoint
  #     dockerfile: ./Dockerfile
  #   container_name: endpoint
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./queries:/app/queries
  #     - ./results:/appresults