version: "3.3"
services:

  qdrant-db:
    image: qdrant/qdrant:master
    ports:
      - "6333:6333"
    volumes:
      - ./path/to/data:/qdrant/storage
      - ./qdrant/evelopment.yaml:/qdrant/config/development.yaml

  # very much psuedo-code
  interface:
    build:
      context: ./interface
      dockerfile: ./Dockerfile
    container_name: interface
    ports:
      - "8501:8501"
    volumes:
      - ./queries:/interface/queries
      - ./results:/interface/results

  api:
    build:
      context: ./endpoint
      dockerfile: ./Dockerfile
    container_name: api
    ports:
      - "8000:8000"
    volumes:
      - ./queries:/interface/queries
      - ./results:/interface/results